[mgr]
linemode = "size_and_mtime"
show_hidden = false
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Edit in nvim", for = "unix" },
]

[open]
prepend_rules = [
  { name = "*.tex", use = "edit" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
name = "*.md"
run = "piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula \"$1\""

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "ouch"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run = "ouch"

[[plugin.prepend_previewers]]
name = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.ipynb"
run = "rich-preview"
